-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 18:37:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bbs_scut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbs_scut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbs_scut` DEFAULT CHARACTER SET utf8 ;
USE `bbs_scut` ;

-- -----------------------------------------------------
-- Table `bbs_scut`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`administrator` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(45) NOT NULL,
  `login_passwd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbs_scut`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_gender` INT(11) NULL DEFAULT '0',
  `user_fans` INT(11) NULL DEFAULT '0',
  `user_selfinfo` VARCHAR(45) NULL DEFAULT NULL,
  `user_face` VARCHAR(100) NULL DEFAULT NULL,
  `user_concern` INT(11) NULL DEFAULT NULL,
  `nick_name` VARCHAR(45) NULL DEFAULT 'null',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbs_scut`.`attention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`attention` (
  `author_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `attention_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`attention_id`),
  CONSTRAINT `author_id_foreign`
    FOREIGN KEY (`author_id`)
    REFERENCES `bbs_scut`.`user` (`user_id`),
  CONSTRAINT `user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `bbs_scut`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_id_foreign` ON `bbs_scut`.`attention` (`user_id` ASC) ;

CREATE INDEX `author_id_foreign` ON `bbs_scut`.`attention` (`author_id` ASC) ;


-- -----------------------------------------------------
-- Table `bbs_scut`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`article` (
  `article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `create_time` DATE NULL DEFAULT NULL,
  `likes_num` INT(11) NULL DEFAULT '0',
  `dislikes_num` INT(11) NULL DEFAULT '0',
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bbs_scut`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_id` ON `bbs_scut`.`article` (`user_id` ASC) ;


-- -----------------------------------------------------
-- Table `bbs_scut`.`articlecollection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`articlecollection` (
  `collection_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `article_id` INT(11) NOT NULL,
  PRIMARY KEY (`collection_id`),
  CONSTRAINT `col_article_id_foreign`
    FOREIGN KEY (`article_id`)
    REFERENCES `bbs_scut`.`article` (`article_id`),
  CONSTRAINT `col_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `bbs_scut`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `col_article_id_foreign` ON `bbs_scut`.`articlecollection` (`article_id` ASC) ;

CREATE INDEX `col_user_id_foreign` ON `bbs_scut`.`articlecollection` (`user_id` ASC) ;


-- -----------------------------------------------------
-- Table `bbs_scut`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbs_scut`.`comment` (
  `comment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `time` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `com_article_id`
    FOREIGN KEY (`article_id`)
    REFERENCES `bbs_scut`.`article` (`article_id`),
  CONSTRAINT `com_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `bbs_scut`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `com_article_id` ON `bbs_scut`.`comment` (`article_id` ASC) ;

CREATE INDEX `com_user_id` ON `bbs_scut`.`comment` (`user_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
